### ISSUE TITLE
Repack Fonts

### ISSUE THREAD

**Issue by michalss** [Atvaark/FtexTool#3]
Hi Mate,

Found a problem with texture repacker.. Once you repack fonts, just pure repack without any modifications this will happend :( Can anyone please help ??
Can you please have a look on that texture problem ?? you can find it in data_01\Assets\tpp\ui\Font\Font_RodinProN_DB_def_alp.ftex, in game it is first cinematics with subtitiles. I think, mipmaps in fonts textures are wrong...

http://s25.postimg.org/5fqkp8ain/Mgs_Ground_Zeroes_2015_03_08_09_56_05_36.png

**Comment by Atvaark** [comment]
Hi michalss,

this isn't a problem with the tool per se.
What Ground Zeroes does is it tries to read the original texture, which happens to be chunked differently after repacking it. This happens because the ftex and ftexs files are stored redundantly for faster read access.

For this texture in particular you have to also edit the file in the following texture archives:
* gz_ui_default_data.pftxs
* gz_ui_default_data_stream.pftxs
* title_datas.pftxs
