### ISSUE TITLE
Does not support 3D LUT.

### ISSUE THREAD

**Issue by Joey35233** [Atvaark/FtexTool#9]
texture0\Assets\fox\effect\gr_pic\reflection_planes_nomip_rgba32.ftex unpacks to a DDS instead of a volume texture.

**Comment by Atvaark** [comment]
Are you sure it isn't a DDS with volume flags?

**Comment by Joey35233** [comment]
Not sure. According to the Fox shader source code the BRDF uses 3 LUTs, one
labeled a Texture3D and we believe with decent certainly that LUT, aka
g_lut2 is that reflection_plane texture. What is the difference between a
3d texture and a texture with volume flags?

**Comment by Joey35233** [comment]
Oh, I see what you mean. Sorry, it should be a dds but it doesn't seem to have all of the slices, just one. That's what I mean.

**Comment by Atvaark** [comment]
Would you mind uploading the files somewhere?
Maybe the ftex file doesn't have depth values set or isn't of [type 0](https://github.com/Atvaark/FtexTool/blob/83e7c25f9f9f7d485d2ffbae0953aac473aa5919/FtexTool/FtexDdsConverter.cs#L30).

**Comment by Joey35233** [comment]
Sure. Here is the code. Not sure if you know HLSL or not, but this shows it
should be this one and it should be a 3D texture.

*half lookupSpecularPower( float HN, half roughness, half anisoRoughness )
{ float3 uv ; uv.x = saturate( HN ); uv.y = roughness ; uv.z =
anisoRoughness ; uv.xyz <http://uv.xyz> = uv.xyz <http://uv.xyz> * uv.xyz
<http://uv.xyz> ; float4 correctParam = float4( 63.0/64.0, 15.0/16.0,
0.5/64.0, 0.5/16.0 ); uv.xyz <http://uv.xyz> = uv.xyz <http://uv.xyz> *
correctParam.xyy + correctParam.zww ; half2 value = TFetch3DH( g_lut2,
SamplerLinearClamp, uv.xyz <http://uv.xyz> ).xy ; value.xy = value.xy *
value.xy ; return value.x / value.y ; }*

**Comment by Atvaark** [comment]
I was talking about the ftex/ftexs files that are apparently missing dimensions when converted to DDS.

**Comment by Joey35233** [comment]
Yes. They were attached.

**Comment by Atvaark** [comment]
Github drops email attachments. You have to either host them somewhere externally or attach them when replying directly on Github.

**Comment by Joey35233** [comment]
Sorry this has taken so long. [Here](https://drive.google.com/file/d/0B9WDsG6I-SGEWHNlLWJuZ3pmcFlsdVd5VmFoUExkblk5M1JF/view?usp=drivesdk) is the .ftex and [here](https://drive.google.com/file/d/0B9WDsG6I-SGEWHNlLWJuZ3pmcFlsdVd5VmFoUExkblk5M1JF/view?usp=drivesdk) is the .ftexs

**Comment by Joey35233** [comment]
Didn't mean to close it.

**Comment by Atvaark** [comment]
The ftex files is actually just 128x128x1. But the converted DDS file should have the volume flag set and the A8R8G8B8 pixel format.

**Comment by Joey35233** [comment]
So it's a volume texture with 1 slice? Odd.

**Comment by Chuny-PES** [comment]
Hello everybody!
I'm new here.

I just registered here because I seem to have a similar problem.
Let me try to explain this as briefly as I can.

Here's the default original file, from the game (PES 2018) : http://www19.zippyshare.com/v/YO2wksv1/file.html

I converted it to DDS, edited in Photoshop, but I don't know which options to select when I want to export it back to DDS in order to then convert it to FTEX.

In the previous year version, I could save the LUT as DDS with the following format:
**32.32.32.32f ABGR 128 bpp | floating point
Volume Texture
Generate Mipmaps**

And the game would simply read that DDS by itself. But this year they changed the file formats to FTEXs so I need to convert the DDS to FTEX in order for the game to read the LUT file.

I hope you can help me out!

THANKS A LOT!

**Comment by Atvaark** [comment]
Please see the other issues for PES related problems.
